# Web服务器配置
server:
  # 端口号
  port: 8989

# ----------------------------------------------------------------------

# Spring相关配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/briup_cms?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Shanghai
    username: root
    password: 5521815

# ----------------------------------------------------------------------

  # Redis配置
  redis:
    # Redis装在本机的话可以写localhost 或 127.0.0.1
    host: 192.168.180.4
    # 端口号
    port: 16379
    # 认证密码
    password: briupSH123...
    # 定义要使用的数据库索引（默认为0）
    database: 0

    jedis:
      # 连接池设置
      pool:
        # 连接池最大连接数
        max-active: 200
        # 最大阻塞等待时间（-1表示无限制）
        max-wait: -1
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 0

# ----------------------------------------------------------------------

# MyBatis相关配置
mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    # 开启MyBatis执行日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ----------------------------------------------------------------------

# MyBatisPlus相关配置
mybatis-plus:
  global-config:
    db-config:
      # 逻辑删除中表示删除状态的字段值（默认为1）
      logic-delete-value: 1
      # 逻辑删除中表示未删除状态的字段值（默认为0）
      logic-not-delete-value: 0
      # 定义表示逻辑删除状态的字段名（可以通过TableLogic注解声明）
      logic-delete-field: deleted
  configuration:
    # 开启下划线命名和驼峰命名之间的自动映射转换功能
    map-underscore-to-camel-case: true

# ----------------------------------------------------------------------

# 日志相关配置
logging:
  # 日志输出级别
  level:
    root: info

# ----------------------------------------------------------------------

# 自定义配置
briup:
  config:
    ## OSS七牛云存储配置 ##
    # 桶名称（存储空间名称）
    oss-bucket: briup-avatar-yy2
    # 公钥
    oss-access-key: Rmcja6GTqodOBYediQ_xn7B951mJOqPiifUqr5kc
    # 私钥
    oss-secret-key: t6RmBH49vzEjffNljlhDDUpAKudAiYJW18ti0Rch
    # URL固定前缀
    oss-base-url: http://s4gslnfvl.hn-bkt.clouddn.com/
    # 默认文件名称
    oss-default-file-name: noname.jpg

    ## 加密相关配置 ##
    # 加密强度
    security-strength: 6
    # 干扰因子（使用随机UUID生成）
    security-secret: ${random.uuid}

    ## 跨域配置 ##
    # 允许跨域访问的资源
    cors-mapping: "/**"
    # 允许跨域访问的客户端源
    cors-allowed-origins: "*"
    # 允许跨域访问使用的HTTP请求方法
    cors-allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
    # 允许跨域访问携带的HTTP请求头部
    cors-allowed-headers: "*"
    # 是否允许携带Cookie
    cors-allow-credentials: false
    # 预检请求缓存有效时长（单位：秒）
    cors-max-age: 3600

    ## 访问权限配置 ##
    # 需要拦截的请求URL
    auth-include-path-patterns: /**
    # 不需要拦截的请求URL
    auth-exclude-path-patterns:
      - /login
      - /logout
      - /upload
      - /auth/category/**
      - /auth/log/**
      - /slideshow/**

    ## 导出、下载相关配置 ##
    # 导出Excel使用的编码格式
    excel-export-encoding: UTF-8
    # 导出Excel的文件类型（Office2003之前对应XLS，Office2003之后对应XLSX）
    excel-export-file-type: XLSX
    # 导出Excel时使用的Content-Type头部字段值
    excel-export-content-type: application/octet-stream;charset=${briup.config.excel-export-encoding}
    # 导出Excel时使用的Content-Disposition头部字段值
    excel-export-content-disposition: attachment;filename=%s

    ## 其他配置 ##
    # 默认时间格式（解析请求参数时使用）
    default-date-pattern: yyyy-MM-dd HH:mm:ss
    # IP查询服务地址
    ip-query-server-host: http://whois.pconline.com.cn/ipJson.jsp
